# Use the official Go Docker image as the base image
FROM golang:latest

# Install Python 3 and required packages
RUN apt-get update \
    && apt-get install -y python3 \
    && apt-get install -y python3-setuptools \
    && apt-get install -y python3-pip \
    && apt-get clean

# Set the working directory inside the container
WORKDIR /app

# Copy your Go source code into the container
COPY . .

# Build your Go application
RUN go build -o myapp .

# Command to run your Go application
CMD ["./myapp"]
